import {lazy,Suspense,useCallback,useEffect,useMemo,useState} from 'react';
import {sampleAt} from './contracts.js';
import {evidenceBase,readVerified} from './load.js';
import {Plot} from './diagnosis.js';
import {COHORTS,validateApproachIndex,validateApproach,parseSelection,selectionHash,reviewExport,type ApproachCase,type Approach} from './approach-contract.js';
import './approach.css';
const Scene=lazy(()=>import('./scene.js'));
const MODES=['baseline','candidate'] as const;
const fmt=(v:number|null|undefined,n=3)=>v==null?'Not measured':v.toFixed(n);
const pairSeries=[{name:'Fixed gains',column:1,color:'#70baff'},{name:'Scheduled gains',column:2,color:'#68e2bc'}];
export function ApproachWorkspace({baseUrl,indexSha256}:{baseUrl:string;indexSha256:string}){
  const initial=useMemo(()=>parseSelection(location.hash,indexSha256),[indexSha256]);
  const [cases,setCases]=useState<ApproachCase[]>([]),[selected,setSelected]=useState(initial?.id??'stress-p0-s401'),[data,setData]=useState<Approach|null>(null),[error,setError]=useState('');
  const [time,setTime]=useState(initial?.time??40),[relative,setRelative]=useState(initial?.relative??false),[playing,setPlaying]=useState(false);
  const [cohort,setCohort]=useState('all'),[filter,setFilter]=useState('all');
  const [show3d,setShow3d]=useState(false),[failed3d,setFailed3d]=useState(false),[visible,setVisible]=useState(!document.hidden),[share,setShare]=useState('');
  const fail=useCallback(()=>setFailed3d(true),[]);
  useEffect(()=>{const controller=new AbortController();setError('');setCases([]);
    void readVerified(new URL('index.json',evidenceBase(baseUrl,location.origin)),indexSha256,controller.signal,16384).then(v=>{if(!controller.signal.aborted)setCases(validateApproachIndex(v));}).catch(()=>{if(!controller.signal.aborted)setError('Verified study index unavailable. Prepare an approach export.');});return()=>controller.abort();
  },[baseUrl,indexSha256]);
  useEffect(()=>{setData(null);setPlaying(false);setError('');setFailed3d(false);setShare('');if(!cases.length)return;
    const controller=new AbortController(),entry=cases.find(c=>c.id===selected)!;
    void readVerified(new URL(entry.file,evidenceBase(baseUrl,location.origin)),entry.sha256,controller.signal,12*1024*1024).then(v=>{const pair=validateApproach(v,entry);if(!controller.signal.aborted)setData(pair);}).catch(()=>{if(!controller.signal.aborted)setError('Comparison failed integrity or consistency checks. No unverified flight is displayed.');});return()=>controller.abort();
  },[cases,selected,baseUrl]);
  const end=data?Math.min(...MODES.map(m=>data[m].rows.at(-1)?.[0]??34)):50,hasRows=!!data&&MODES.every(m=>data[m].rows.length>1);
  const offset=relative?40:0;
  useEffect(()=>{setTime(t=>Math.max(34,Math.min(end,t)));},[end]);
  useEffect(()=>{const hide=()=>{setVisible(!document.hidden);if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
  useEffect(()=>{if(!playing||!visible||!hasRows)return;let id=0,previous=0;const tick=(now:number)=>{if(previous)setTime(t=>{const next=Math.min(end,t+Math.min((now-previous)/1000,.1)*.5);if(next>=end)setPlaying(false);return next;});previous=now;id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing,visible,end,hasRows]);
  const filtered=cases.filter(c=>(cohort==='all'||c.cohort===cohort)&&(filter==='all'||filter==='failed'&&(c.baseline_status==='failed'||c.candidate_status==='failed')||filter==='regressed'&&c.regressed_gates>0));
  const seek=(t:number)=>{setPlaying(false);setTime(Math.max(34,Math.min(end,Math.round(t/.005)*.005)));setShare('');};
  const curves=useMemo(()=>[31,33,34].map(column=>data&&hasRows?data.baseline.rows.filter(r=>r[0]<=end).map((r,i)=>[r[0]-offset,r[column],data.candidate.rows[i][column]]):[]),[data,hasRows,end,offset]);
  function shareSelection(){const hash=selectionHash({id:selected,time,relative},indexSha256);history.replaceState(null,'',location.pathname+hash);setShare(location.origin+location.pathname+hash);}
  function download(){if(!data)return;const content=reviewExport(data,{id:selected,time,relative},indexSha256),url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${selected}-approach.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <main className="dg ds ag"><header className="dg-header"><a href="/contact.html">AEROLOOP / SIMULATION LAB</a><span>Recorded PhysX · simulation only</span></header>
    <div className="dg-hero"><div><p className="dg-eyebrow">CONTROL EXPERIMENT / 03</p><h1>Hold the approach.<br/>Measure the tradeoff.</h1><p>One fixed horizontal gain schedule, tested against turbulent landings with noisy, delayed feedback.</p></div><div className="dg-summary"><strong>{cases.length||'—'}</strong><span>paired cases · three cohorts</span><strong>2.5 → 4.0</strong><span>horizontal position gain · s⁻²</span><strong>2.8 → 3.6</strong><span>horizontal velocity gain · s⁻¹</span></div></div>
    {error&&<p className="dg-alert" role="alert">{error}</p>}
    <section className="dg-panel"><h2>01 / Cohort outcomes</h2><p>Mission results from the original gates. Gate regressions count passed → failed or missing; gains remain opt-in.</p><div className="ds-table"><table aria-label="Cohort outcomes"><thead><tr><th>Cohort</th><th>Fixed missions</th><th>Scheduled missions</th><th>Pairs with gate regressions</th></tr></thead><tbody>{COHORTS.map(c=>{const group=cases.filter(x=>x.cohort===c);return <tr key={c}><td>{c}</td><td>{group.filter(x=>x.baseline_status==='passed').length} / {group.length}</td><td>{group.filter(x=>x.candidate_status==='passed').length} / {group.length}</td><td>{group.filter(x=>x.regressed_gates>0).length} / {group.length}</td></tr>;})}</tbody></table></div><p>Regression and stress baselines are retained flights; stress seeds were previously observed. Additional seeds were declared before this experiment.</p></section>
    <section className="dg-panel ds-controls"><label>Cohort<select aria-label="Cohort" value={cohort} onChange={e=>setCohort(e.target.value)}><option value="all">All cohorts</option>{COHORTS.map(c=><option key={c}>{c}</option>)}</select></label><label>Filter<select aria-label="Outcome filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All results</option><option value="failed">Either mission failed</option><option value="regressed">Any original gate regressed</option></select></label><p>{filtered.length} / {cases.length} cases visible</p>
      <div className="ag-cases">{filtered.map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>{setSelected(c.id);setTime(40);}}>{c.cohort} · {c.seed} · {c.profile==='sample-hold'?'no outage':'2 s outages'}<small>{c.baseline_status} → {c.candidate_status} · {c.improved_gates} improved / {c.regressed_gates} regressed gates</small></button>)}</div>{!filtered.length&&<p>No cases match this filter. The selected comparison below stays available.</p>}
    </section>
    {data&&<><section className="dg-panel ds-timeline"><h2 data-testid="selected-case">02 / {data.cohort} · seed {data.seed} · {data.profile==='sample-hold'?'no outage':'2 s outages'}</h2>
      <div><button disabled={!hasRows} onClick={()=>{if(time>=end)setTime(34);setPlaying(v=>!v);}}>{playing?'Pause':'Play ½×'}</button><button disabled={!hasRows} onClick={()=>seek(time-.005)}>Previous step</button><button disabled={!hasRows} onClick={()=>seek(time+.005)}>Next step</button><strong data-testid="cursor">{fmt(time-offset)} s {relative?'from gust':'simulation time'}</strong></div>
      <input aria-label="Comparison time" type="range" min={34} max={end} step=".005" value={time} disabled={!hasRows} onChange={e=>seek(Number(e.target.value))}/>
      <div className="ag-chapters">{[['Ramp start',34],['Ramp complete',35],['Gust start',40],['Gust end',42]].map(([label,t])=><button key={label} disabled={!hasRows||Number(t)>end} onClick={()=>seek(Number(t))}>{label}</button>)}<label><input type="checkbox" checked={relative} onChange={e=>{setRelative(e.target.checked);setShare('');}}/>Gust-relative time</label></div>
      <div className="ag-chapters"><button onClick={()=>setShow3d(v=>!v)}>{show3d?'Hide 3D':'Enable paired 3D'}</button><button onClick={shareSelection}>Share review</button><button onClick={download}>Export review JSON</button></div>
      {share&&<label className="ds-share">Review link<input aria-label="Review link" readOnly value={share} onFocus={e=>e.target.select()}/><small>Bound to this evidence version on a machine serving the same local demo.</small></label>}
      <p>5 ms numeric cursor · interpolated 3D display · shaded interval is the 40–42 s landing gust, and also the second outage when enabled.</p>
    </section>
    <div className="ds-pair">{MODES.map(mode=>{const s=data[mode],r=s.rows[Math.max(0,Math.min(s.rows.length-1,Math.floor((time-34+1e-8)/.005)))],d=s.diagnostics;
      return <section className="dg-panel ds-side" aria-label={mode} key={mode}><h2>{mode==='baseline'?'Fixed horizontal gains':'Scheduled horizontal gains'}</h2><p className={s.status==='failed'?'dg-alert':''}>Mission <strong>{s.status.toUpperCase()}</strong> · {s.failure_reason?.replaceAll('_',' ')??'all original mission gates passed'}</p><p>{s.outage?`Same-mode outage pair: ${s.outage.passed?'passed':'failed'} · sustained recovery ${s.outage.recovery.filter(w=>w.passed).length}/2`:'No-outage reference · pair and recovery not applicable'}</p>
        {show3d&&!failed3d&&<div className="dg-scene"><Suspense fallback={<p>Loading 3D…</p>}><Scene sample={sampleAt(s.poses,Math.min(time,s.poses.at(-1)!.time_s))} samples={s.poses} rotorFlight visible={visible} onFailure={fail}/></Suspense></div>}{failed3d&&<p>3D unavailable. Numeric diagnostics remain available.</p>}
        <div className="ag-chapters"><button disabled={s.touchdown_s===null||s.touchdown_s>end} onClick={()=>seek(s.touchdown_s!)}>Jump to contact</button><button disabled={s.landed_s===null||s.landed_s>end} onClick={()=>seek(s.landed_s!)}>Jump to disarm</button></div><p>Contact {fmt(s.touchdown_s)} s · disarm {fmt(s.landed_s)} s</p>
        {!r?<p className="dg-alert">No landing samples. Missing coverage is not a pass.</p>:<><p className="ds-clock">Gain blend {fmt(r[17]*100,1)}% · Kp {fmt(r[18])} s⁻² · Kd {fmt(r[19])} s⁻¹<br/>Horizontal error {fmt(r[31])} m · speed {fmt(r[32])} m/s</p><p>Clipped X/Y demand {fmt(r[20])} / {fmt(r[21])} m/s² · axis clipping {r[35]?'active':'inactive'} · allocation {fmt((1-r[22])*100,2)}% reduction ({fmt(r[22]*100,2)}% authority retained).</p><p>Wind X/Y {fmt(r[23])} / {fmt(r[24])} N · world thrust X/Y {fmt(r[25])} / {fmt(r[26])} N · tilt {fmt(r[37])}°</p></>}
        <h3>34 s → final sample</h3><dl className="ag-metrics"><div><dt>Squared tracking-error integral</dt><dd>{fmt(d.squared_error_integral_m2_s)} m² s</dd></div><div><dt>Squared acceleration-demand integral</dt><dd>{fmt(d.squared_demand_integral_m2_s3)} m²/s³</dd></div><div><dt>Axis clipping occupancy</dt><dd>{fmt(d.axis_clipped_fraction==null?null:d.axis_clipped_fraction*100,2)}%</dd></div><div><dt>Minimum allocation scale</dt><dd>{fmt(d.minimum_allocation_scale,4)}</dd></div></dl><p>{d.samples} / 3201 landing samples · {d.complete?'complete':'incomplete'}. Integrals are descriptive; commanded demand is not energy.</p>
        <details><summary>Recording identity and same-mode outage results</summary><p>Clean source {s.provenance.source_commit}</p><p>Samples SHA-256 {s.provenance.samples_sha256}</p>{s.outage&&<p>Peak separation {fmt(s.outage.peak_distance_m)} m · RMSE shift {fmt(s.outage.rmse_change_m)} m · landing shift {fmt(s.outage.landed_change_s)} s · recovery {s.outage.recovery.map(w=>fmt(w.time_s)).join(' / ')} s</p>}</details>
      </section>;
    })}</div>
    {hasRows&&<section className="dg-panel"><h2>03 / Tracking and demand</h2>{['Horizontal tracking error · m','Cumulative squared error · m² s','Cumulative squared demand · m²/s³'].map((title,i)=><Plot key={title} title={title} rows={curves[i]} start={34-offset} end={end-offset} time={time-offset} onSeek={t=>seek(t+offset)} windows={[[40-offset,42-offset]]} series={pairSeries}/>)}<p>Integrals use the preceding recorded value over each interval [34,t). No extra interval is added at the final sample. Both curves stop at their common available end.</p></section>}
    <section className="dg-panel"><h2>04 / Original-gate changes</h2><p>Positive headroom change means more margin in the gate’s own units. An unchanged failed gate remains failed.</p><div className="ds-table"><table aria-label="Original-gate changes"><thead><tr><th>Gate</th><th>Limit</th><th>Fixed</th><th>Scheduled</th><th>Change</th><th>Margin Δ</th></tr></thead><tbody>{data.gate_changes.map((c,i)=>{const a=data.baseline.gates[i],b=data.candidate.gates[i];return <tr key={c.id} className={`ag-${c.change}`}><td>{a.label}</td><td>{a.operator} {a.limit} {a.unit}</td><td>{fmt(a.value)} · {a.status}</td><td>{fmt(b.value)} · {b.status}</td><td>{c.change}</td><td>{fmt(c.headroom_delta)} {a.unit}</td></tr>;})}</tbody></table></div></section></>}
    <footer className="dg-panel"><p>24 fresh final PhysX flights and 12 retained baselines. Development seed 83 is excluded. The scheduled gains affect only horizontal approach control, blending over 34–35 s; altitude control and original acceptance limits are fixed. Failures remain visible.</p><p>Small synthetic cohorts, ideal attitude/contact supervision, simplified wind/rotors and unresolved yaw refinement limit these results. Soft real-time monitoring is provisional; full-rate recordings determine outcomes. Simulation only.</p></footer>
  </main>;
}
