import {lazy,Suspense,useCallback,useEffect,useMemo,useState} from 'react';
import {sampleAt} from './contracts.js';
import {evidenceBase,readVerified} from './load.js';
import {Plot} from './diagnosis.js';
import {MODES,DEFAULT_BOUNDS,validateContactIndex,validateContact,episodes,phases,readiness,contactExport,selectionHash,parseSelection,type Bounds,type Contact,type ContactCase} from './contact-contract.js';
import './contact.css';
const Scene=lazy(()=>import('./scene.js'));
const fmt=(v:number|null|undefined,n=3)=>v==null?'Not measured':v.toFixed(n);
const series=(items:[string,number,string][])=>items.map(([name,column,color])=>({name,column,color}));
const colors=['#68e2bc','#c19bff','#70baff','#e7b16a','#f394b9'];
const TERMS=(axis:number)=>series([['P',33+axis,colors[0]],['D',35+axis,colors[1]],['Integral',13+axis,colors[2]],['Feedforward',15+axis,colors[3]],['Clipped sum',37+axis,colors[4]]]);
const ROTORS=series([['Rotor 0',21,colors[0]],['Rotor 1',22,colors[1]],['Rotor 2',23,colors[2]],['Rotor 3',24,colors[3]]]);
const MOTION=series([['Distance from home · m',43,colors[0]],['Horizontal speed · m/s',44,colors[1]]]);
const FEEDBACK=series([['Position error · m',45,colors[0]],['Velocity error · m/s',46,colors[1]]]);
const ATTITUDE=series([['Tilt',41,colors[0]],['Yaw',42,colors[1]]]);
const FORCE=series([['Thrust X',39,colors[0]],['Thrust Y',40,colors[1]],['Wind X',25,colors[2]],['Wind Y',26,colors[3]]]);

function Map({rows,row,id}:{rows:number[][];row:number[];id:string}){
  const scale=useMemo(()=>Math.max(.5,...rows.flatMap(r=>[Math.abs(r[1]),Math.abs(r[2]),Math.abs(r[5]),Math.abs(r[6]),Math.abs(r[1]+.5*r[3]),Math.abs(r[2]+.5*r[4])]))*1.1,[rows]);
  const x=(v:number)=>200+v/scale*170,y=(v:number)=>190-v/scale*170;
  const path=(a:number,b:number)=>rows.map((r,i)=>`${i?'L':'M'}${x(r[a]).toFixed(2)},${y(r[b]).toFixed(2)}`).join(' ');
  return <div className="ct-map"><svg viewBox="0 0 400 400" role="img" aria-label="Horizontal landing map">
    <defs><marker id={`arrow-${id}`} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#e7b16a"/></marker></defs>
    <line x1="30" x2="370" y1="190" y2="190" stroke="#34455b"/><line x1="200" x2="200" y1="20" y2="360" stroke="#34455b"/>
    <circle cx={x(0)} cy={y(0)} r={.35/scale*170} fill="#68e2bc" fillOpacity=".04" stroke="#68e2bc" strokeDasharray="4 5"/>
    <path d={path(5,6)} fill="none" stroke="#c19bff" opacity=".45"/><path d={path(1,2)} fill="none" stroke="#68e2bc"/>
    <line x1={x(row[1])} y1={y(row[2])} x2={x(row[1]+.5*row[3])} y2={y(row[2]+.5*row[4])} stroke="#e7b16a" strokeWidth="2" markerEnd={`url(#arrow-${id})`}/>
    <circle cx={x(row[1])} cy={y(row[2])} r="5" fill="#68e2bc"/><circle cx={x(row[5])} cy={y(row[6])} r="4" fill="#c19bff"/>
    <text x="205" y="185">Home</text><text x="30" y="390">±{fmt(scale,2)} m · X right / Y up · equal scale</text>
  </svg><p>Truth in green · applied feedback in purple. Circle: 0.35 m final-support limit. Arrow: current velocity × 0.5 s, not a predicted path.</p></div>;
}

export function ContactWorkspace({baseUrl,indexSha256}:{baseUrl:string;indexSha256:string}){
  const initial=useMemo(()=>parseSelection(location.hash,indexSha256),[indexSha256]);
  const [cases,setCases]=useState<ContactCase[]>([]),[selected,setSelected]=useState(initial?.id??'additional-p0-s401'),[data,setData]=useState<Contact|null>(null),[error,setError]=useState('');
  const [cohort,setCohort]=useState('all'),[failedOnly,setFailedOnly]=useState(false),[ranked,setRanked]=useState(true);
  const [time,setTime]=useState(initial?.time??41.68),[bounds,setBounds]=useState<Bounds>(initial?.bounds??DEFAULT_BOUNDS),[share,setShare]=useState(''),[playing,setPlaying]=useState(false);
  const [show3d,setShow3d]=useState(false),[failed3d,setFailed3d]=useState(false),[visible,setVisible]=useState(!document.hidden);
  const fail=useCallback(()=>setFailed3d(true),[]);
  useEffect(()=>{const abort=new AbortController();setCases([]);setError('');
    void readVerified(new URL('index.json',evidenceBase(baseUrl,location.origin)),indexSha256,abort.signal,16384).then(v=>{if(!abort.signal.aborted)setCases(validateContactIndex(v));}).catch(()=>{if(!abort.signal.aborted)setError('Verified contact index unavailable. Prepare a landing contact export.');});return()=>abort.abort();
  },[baseUrl,indexSha256]);
  useEffect(()=>{setData(null);setPlaying(false);setError('');setFailed3d(false);setShare('');if(!cases.length)return;
    const abort=new AbortController(),entry=cases.find(c=>c.id===selected);if(!entry){setError('Case absent from this study.');return;}
    void readVerified(new URL(entry.file,evidenceBase(baseUrl,location.origin)),entry.sha256,abort.signal,24*1024*1024).then(v=>{const d=validateContact(v,entry);if(!abort.signal.aborted)setData(d);}).catch(()=>{if(!abort.signal.aborted)setError('Landing evidence failed integrity or consistency checks. No unverified flight is displayed.');});return()=>abort.abort();
  },[cases,selected,baseUrl]);
  const end=data?Math.min(...MODES.map(m=>data[m].at(-1)?.[0]??34)):50;
  useEffect(()=>{if(data)setTime(t=>Math.max(34,Math.min(end,t)));},[data,end]);
  useEffect(()=>{const hide=()=>{setVisible(!document.hidden);if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
  useEffect(()=>{if(!playing||!visible)return;let id=0,previous=0;const tick=(now:number)=>{if(previous)setTime(t=>{const next=Math.min(end,t+Math.min((now-previous)/1000,.1)*.5);if(next>=end)setPlaying(false);return next;});previous=now;id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing,visible,end]);
  const queue=useMemo(()=>{const list=cases.filter(c=>(cohort==='all'||cohort===c.cohort)&&(!failedOnly||MODES.some(m=>c[`${m}_status`]==='failed')));
    return ranked?list.sort((a,b)=>Math.max(b.baseline_support_error_m??-1,b.candidate_support_error_m??-1)-Math.max(a.baseline_support_error_m??-1,a.candidate_support_error_m??-1)):list;
  },[cases,cohort,failedOnly,ranked]);
  const summaries=useMemo(()=>data?MODES.map(m=>({episodes:episodes(data.descent[m]),phases:phases(data[m],data.descent[m]),audit:readiness(data[m],data.descent[m],bounds)})):[],[data,bounds]);
  const seek=(t:number)=>{setPlaying(false);setTime(Math.max(34,Math.min(end,Math.round(t/.005)*.005)));setShare('');};
  const makeLink=()=>{const hash=selectionHash({id:selected,time,bounds},indexSha256);history.replaceState(null,'',location.pathname+hash);setShare(location.origin+location.pathname+hash);};
  const download=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(contactExport(data,bounds,indexSha256,time))+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${selected}-contact.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <main className="dg ds ct"><header className="dg-header"><a href="/descent.html">AEROLOOP / SIMULATION LAB</a><span>Retained PhysX · simulation only</span></header>
    <div className="dg-hero"><div><p className="dg-eyebrow">LANDING CONTACT LAB / 03</p><h1>From first contact<br/>to motors off.</h1><p>Trace horizontal motion, control demand and contact through the landing failures.</p></div><div className="dg-summary"><strong>24</strong><span>retained physics flights</span><strong>200 Hz</strong><span>numeric landing evidence</span><strong>10</strong><span>inspection and review tools</span></div></div>
    {error&&<p className="dg-alert" role="alert">{error}</p>}
    <section className="dg-panel"><h2>Landing review queue</h2><div className="ds-controls"><label>Cohort<select aria-label="Cohort" value={cohort} onChange={e=>setCohort(e.target.value)}><option value="all">Both cohorts</option><option value="regression">Regression</option><option value="additional">Additional</option></select></label><label><input type="checkbox" checked={failedOnly} onChange={e=>setFailedOnly(e.target.checked)}/>Failed missions only</label><label><input type="checkbox" checked={ranked} onChange={e=>setRanked(e.target.checked)}/>Rank by worst support error</label></div>
      <div className="ds-table ct-queue"><table><thead><tr><th>Case</th><th>Original / decay mission</th><th>Final support error · m</th></tr></thead><tbody>{queue.map(c=><tr key={c.id} aria-selected={selected===c.id}><td><button aria-pressed={selected===c.id} onClick={()=>{setSelected(c.id);setTime(41.68);}}>{c.cohort} · {c.seed} · {c.profile==='sample-hold'?'no outage':'2 s outage'}</button></td><td>{c.baseline_status} / {c.candidate_status}</td><td>{fmt(c.baseline_support_error_m)} / {fmt(c.candidate_support_error_m)}</td></tr>)}</tbody></table></div><p>{queue.length} paired cases shown. Ranking uses the original final-support gate; missing measurements sort last. The selected case remains visible below when filtered out.</p></section>
    <section className="dg-panel ct-audit"><h2>Offline readiness audit</h2><p>Explore a predicate on recorded truth up to actual disarm. These settings cannot change the trajectory, operate motors or establish that a different supervisor would succeed.</p><div className="ct-bounds">{([['position','Distance from home · m',.01,1,.01],['speed','Horizontal speed · m/s',0,1,.01],['tilt','Tilt · degrees',0,25,.1],['dwell','Continuous dwell · s',.005,1,.005]] as const).map(([key,label,min,max,step])=><label key={key}>{label}<input aria-label={label} type="range" min={min} max={max} step={step} value={bounds[key]} onChange={e=>{setBounds(b=>({...b,[key]:Number(e.target.value)}));setShare('');}}/><output>{bounds[key]}</output></label>)}</div><button onClick={()=>{setBounds(DEFAULT_BOUNDS);setShare('');}}>Reset audit bounds</button></section>
    {data&&<><section className="dg-panel ds-timeline"><h2 data-testid="selected-case">{data.descent.cohort} · seed {data.descent.seed} · {data.descent.profile}</h2><div><button disabled={end<=34} onClick={()=>{if(time>=end)setTime(34);setPlaying(v=>!v);}}>{playing?'Pause':'Play ½×'}</button><button disabled={end<=34} onClick={()=>seek(time-.005)}>Previous step</button><button disabled={end<=34} onClick={()=>seek(time+.005)}>Next step</button><button onClick={()=>setShow3d(v=>!v)}>{show3d?'Hide 3D':'Enable paired 3D'}</button><button onClick={makeLink}>Share review</button><button onClick={download}>Export review JSON</button><strong data-testid="cursor">{fmt(time)} s</strong></div><input aria-label="Landing time" type="range" min="34" max={end} step=".005" disabled={end<=34} value={time} onChange={e=>seek(Number(e.target.value))}/>{share&&<label className="ds-share">Review link<input aria-label="Review link" readOnly value={share} onFocus={e=>e.target.select()}/></label>}<p>Shared simulation time. Numeric values use the preceding recorded 5 ms sample; 3D interpolates display poses. Shading marks the 40–42 s outage when present.</p></section>
      <div className="ds-pair">{MODES.map((mode,index)=>{const side=data.descent[mode],rows=data[mode],r=rows[Math.min(rows.length-1,Math.max(0,Math.floor((time-34+1e-9)/.005)))],summary=summaries[index];
        const plot={rows,start:34,end:Math.max(34.005,end),time,onSeek:seek,windows:data.descent.profile==='sample-hold'?[]:[[40,42]]};
        return <section key={mode} className="dg-panel ds-side" aria-label={mode}><h2>{mode==='baseline'?'Original predictor':'Vertical decay candidate'}</h2><p className={side.status==='failed'?'dg-alert':''}>Mission <strong>{side.status.toUpperCase()}</strong> · {side.failure_reason?.replaceAll('_',' ')??'all gates passed'}</p><p>{side.outage?`Same-mode outage pair: ${side.outage.passed?'passed':'failed'} · recovery ${side.outage.recovery.filter(r=>r.passed).length}/2`:'No-outage reference; the candidate is inactive.'}</p>
          <div className="ct-jumps"><button disabled={side.touchdown_s===null||side.touchdown_s>end} onClick={()=>seek(side.touchdown_s!)}>Jump to contact</button><button disabled={side.landed_s===null||side.landed_s>end} onClick={()=>seek(side.landed_s!)}>Jump to disarm</button></div>
          {!r?<p className="dg-alert">No landing samples recorded. The original failed flight remains available for review.</p>:<><p className="ds-clock">Sample {fmt(r[0])} s · distance {fmt(r[43])} m · speed {fmt(r[44])} m/s · energy {fmt(r[47],4)} J</p>
          {show3d&&!failed3d&&<div className="dg-scene"><Suspense fallback={<p>Loading 3D…</p>}><Scene sample={sampleAt(side.poses,time)} samples={side.poses} rotorFlight visible={visible} onFailure={fail}/></Suspense></div>}{failed3d&&<p>3D unavailable. Numeric evidence remains available.</p>}
          <Map rows={rows} row={r} id={mode}/><Plot {...plot} title="Horizontal approach and motion" series={MOTION}/><Plot {...plot} title="Applied feedback minus truth" series={FEEDBACK}/>
          <section className="ds-contact"><h3>Readiness on this trajectory</h3><p>First qualifying time: <strong>{summary.audit.first_qualifying_s===null?'None observed':fmt(summary.audit.first_qualifying_s)+' s'}</strong> · longest eligible dwell {fmt(summary.audit.max_dwell_s)} s.</p><p>Actual disarm: {fmt(side.landed_s)} s. Blocked at that sample by: <strong>{summary.audit.blockers_at_disarm===null?'No disarm recorded':summary.audit.blockers_at_disarm.join(', ')||'none'}</strong>.</p><p>Evaluated through {fmt(summary.audit.evaluated_through_s)} s, {summary.audit.samples} states. Existing contact eligibility is required before the adjustable horizontal/tilt bounds.</p></section>
          <details open><summary>Horizontal controller terms</summary>{[0,1].map(a=><div key={a}><Plot {...plot} title={`${a?'Y':'X'} controller · m/s²`} series={TERMS(a)}/><p>P {fmt(r[33+a])} + D {fmt(r[35+a])} + I {fmt(r[13+a])} + feedforward {fmt(r[15+a])} → clipped {fmt(r[37+a])} m/s².</p></div>)}<p>Applied feedback, recorded integral and fixed original gains. Requested acceleration is not measured acceleration; contact and actuator dynamics intervene.</p></details>
          <details><summary>Actuators and orientation</summary><Plot {...plot} title="Individual rotor thrust · N" series={ROTORS}/><p>Current rotors: {r.slice(21,25).map(v=>fmt(v)).join(' / ')} N. Commanded total {fmt(side.rows[Math.round(r[0]/.005)][11])} N · realized total {fmt(r.slice(21,25).reduce((a,b)=>a+b,0))} N.</p><Plot {...plot} title="World horizontal forces · N" series={FORCE}/><Plot {...plot} title="Tilt and wrapped yaw · degrees" series={ATTITUDE}/><p>Tilt {fmt(r[41])}° · yaw {fmt(r[42])}°. Yaw wraps at ±180°. A zero thrust command still leaves rotor lag.</p></details>
          <details><summary>Momentum and phase budget</summary><p>At {fmt(r[0])} s, Δp = ({fmt(r[3]-r[27],5)}, {fmt(r[4]-r[28],5)}) N·s; residual = ({fmt(r[48],5)}, {fmt(r[49],5)}) N·s. The residual subtracts the preceding interval’s thrust and wind impulse. It includes unrecorded contact/solver effects and numerical error; it is not measured friction.</p><div className="ds-table"><table><thead><tr><th>Phase</th><th>Coverage</th><th>Δ distance · m</th><th>Δ energy · J</th><th>Residual X / Y · N·s</th></tr></thead><tbody>{Object.entries(summary.phases).map(([name,p])=><tr key={name}><td>{name.replaceAll('_',' ')}</td><td>{p?`${fmt(p.start_s)}–${fmt(p.end_s)} s · ${p.complete?'complete':'incomplete'}`:'Not measured'}</td><td>{fmt(p?.distance_change_m)}</td><td>{fmt(p?.energy_change_j,4)}</td><td>{p?.residual_impulse_n_s.map(v=>fmt(v,4)).join(' / ')??'Not measured'}</td></tr>)}</tbody></table></div><div className="ds-table"><table><thead><tr><th>Phase · N·s</th><th>Δ momentum X / Y</th><th>Thrust X / Y</th><th>Wind X / Y</th><th>Residual X / Y</th></tr></thead><tbody>{Object.entries(summary.phases).map(([name,p])=><tr key={name}><td>{name.replaceAll('_',' ')}</td>{(['momentum_change_n_s','thrust_impulse_n_s','wind_impulse_n_s','residual_impulse_n_s'] as const).map(k=><td key={k}>{p?.[k].map(v=>fmt(v,4)).join(' / ')??'Not measured'}</td>)}</tr>)}</tbody></table></div><p>State endpoints are inclusive. Impulses use (start, end], with no duplicated boundary interval. Δ momentum = thrust + wind + residual. Full precision is retained in the export.</p></details>
          <details><summary>Contact episodes ({summary.episodes.length})</summary><p>Consecutive samples with normal force &gt;0.1 N. Duration is last minus first observed contact time. Eligibility also requires clearance and vertical-speed bounds; its dwell resets on interruption.</p><div className="ds-table"><table><thead><tr><th>Jump / start</th><th>Last contact</th><th>Duration</th><th>Eligible states</th><th>Max dwell</th><th>End</th></tr></thead><tbody>{summary.episodes.map(e=><tr key={e.start_s}><td><button disabled={e.start_s>end} onClick={()=>seek(e.start_s)}>{fmt(e.start_s)} s</button></td><td>{fmt(e.end_s)} s</td><td>{fmt(e.duration_s)} s</td><td>{e.eligible_samples}/{e.samples}</td><td>{fmt(e.max_dwell_s)} s</td><td>{e.right_censored?'Recording ended':'Contact lost'}</td></tr>)}</tbody></table></div></details></>}
          <details><summary>Original gates and provenance</summary><div className="ds-table"><table><thead><tr><th>Gate</th><th>Value</th><th>Original limit</th><th>Result</th></tr></thead><tbody>{side.gates.map(g=><tr key={g.id}><td>{g.label}</td><td>{fmt(g.value)} {g.unit}</td><td>{g.operator} {g.limit}</td><td>{g.status}</td></tr>)}</tbody></table></div><p>Clean source {side.provenance.source_commit}</p><p>Samples SHA-256 {side.provenance.samples_sha256}</p><p>Touchdown speed gates use the state preceding contact; cursor speed uses the displayed state.</p></details>
        </section>;
      })}</div></>}
    <footer className="dg-panel"><p>All 24 flights were previously simulated in PhysX and reconstructed for this analysis. No new flight, controller change or robustness improvement is claimed. Original mission, same-mode pair and recovery failures are retained.</p><p>Synthetic sensors, ideal attitude and contact supervision, simplified aerodynamics and unresolved yaw refinement limit the result. Offline readiness never predicts an alternate trajectory. Selection links reopen only where this same evidence bundle is served.</p></footer>
  </main>;
}
