import {lazy,Suspense,useCallback,useEffect,useMemo,useState} from 'react';
import {evidenceBase,readVerified} from './load.js';
import {Plot} from './diagnosis.js';
import {validateIndex,validateFlight,summary,pose,csv,type Case,type Flight} from './friction-contract.js';
import './friction.css';
const Scene=lazy(()=>import('./scene.js'));
const fmt=(v:number|null|undefined)=>v==null?'Unavailable':v.toPrecision(5);
const colors=['#68e2bc','#ff7b9c','#70baff','#fbbf24','#c19bff'];
const series=(labels:string[])=>labels.map((name,i)=>({name,column:i+1,color:colors[i]}));
function save(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function FrictionWorkspace({baseUrl,indexSha256}:{baseUrl:string;indexSha256:string}){
  const [cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState(''),[flight,setFlight]=useState<Flight|null>(null),[error,setError]=useState('');
  const [start,setStart]=useState(40),[end,setEnd]=useState(50),[time,setTime]=useState(42),[playing,setPlaying]=useState(false),[show3d,setShow3d]=useState(false),[failed3d,setFailed3d]=useState(false),[sort,setSort]=useState('id'),[share,setShare]=useState('');
  const fail=useCallback(()=>setFailed3d(true),[]);
  useEffect(()=>{const a=new AbortController();void readVerified(new URL('index.json',evidenceBase(baseUrl,location.origin)),indexSha256,a.signal,65536).then(v=>{if(a.signal.aborted)return;const rows=validateIndex(v);setCases(rows);let id=rows[0].id;const p=new URLSearchParams(location.hash.slice(1));if(p.get('digest')===indexSha256&&rows.some(r=>r.id===p.get('case'))){const s=Number(p.get('start')),e=Number(p.get('end')),t=Number(p.get('time'));if([s,e,t].every(Number.isFinite)&&s>=0&&e<=50&&s<e&&t>=s&&t<=e&&[s,e,t].every(v=>Math.abs(v/.005-Math.round(v/.005))<1e-7)){id=p.get('case')!;setStart(s);setEnd(e);setTime(t);}}setSelected(id);}).catch(()=>{if(!a.signal.aborted)setError('Verified contact index unavailable.');});return()=>a.abort();},[baseUrl,indexSha256]);
  useEffect(()=>{const c=cases.find(c=>c.id===selected);if(!c)return;const a=new AbortController();setFlight(null);setPlaying(false);setError('');setFailed3d(false);setShare('');void readVerified(new URL(c.file,evidenceBase(baseUrl,location.origin)),c.sha256,a.signal,16*1024*1024).then(v=>{const f=validateFlight(v,c);if(!a.signal.aborted)setFlight(f);}).catch(()=>{if(!a.signal.aborted)setError('Contact capture failed integrity or consistency checks.');});return()=>a.abort();},[cases,selected,baseUrl]);
  useEffect(()=>{if(!playing)return;let handle=0,previous=0;const tick=(now:number)=>{if(document.hidden){setPlaying(false);return;}if(previous)setTime(t=>{const v=Math.min(end,t+Math.min(.1,(now-previous)/1000)*.5);if(v>=end)setPlaying(false);return v;});previous=now;handle=requestAnimationFrame(tick);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,end]);
  const metrics=useMemo(()=>flight?summary(flight.rows,start,end):null,[flight,start,end]);
  const poses=useMemo(()=>flight?flight.rows.filter((_,i)=>i%10===0).map(pose):[],[flight]);
  const row=flight?.rows[Math.max(0,Math.min(10000,Math.round(time/.005)))];
  const seek=(t:number)=>{setPlaying(false);setTime(Math.max(start,Math.min(end,Math.round(t/.005)*.005)));setShare('');};
  const curves=useMemo(()=>{if(!flight)return [];const rows=flight.rows.filter(r=>r[0]!>start&&r[0]!<=end);let sums=[0,0,0,0,0];return [rows.map(r=>[r[0]!,Math.hypot(...r.slice(11,14) as number[]),Math.hypot(...r.slice(14,17) as number[])]),rows.map(r=>[r[0]!,r[23]!,r[24]!]),rows.map(r=>{sums=sums.map((v,i)=>v+r[25+i]!);return [r[0]!,...sums];}),rows.filter(r=>r[30]!==null).map(r=>[r[0]!,r[30]!, .5,.7]),rows.filter(r=>r[31]!==null).map(r=>[r[0]!,r[31]!])];},[flight,start,end]);
  function windowChange(s:number,e:number){if(!Number.isFinite(s)||!Number.isFinite(e)||s<0||e>50||s>=e)return;s=Math.round(s/.005)*.005;e=Math.round(e/.005)*.005;if(s>=e)return;setStart(s);setEnd(e);setTime(t=>Math.max(s,Math.min(e,t)));setPlaying(false);setShare('');}
  function exportReview(){if(!flight)return;save(JSON.stringify({schema_version:1,kind:'contact_review',index_sha256:indexSha256,case_sha256:cases.find(c=>c.id===selected)!.sha256,window:{start_s:start,end_s:end},metrics,flight},null,2)+'\n',selected+'-review.json','application/json');}
  return <main className="dg friction"><header className="dg-header"><a href="/response.html">AEROLOOP / CONTACT PHYSICS</a><span>Recorded PhysX · simulation only</span></header>
    <div className="dg-hero"><div><p className="dg-eyebrow">GROUND INTERACTION / 01</p><h1>Measure the force.<br/>Close the balance.</h1><p>Direct ground friction, interval momentum and translational work from fresh turbulent flights.</p></div><div className="dg-summary"><strong>{cases.length||'—'}</strong><span>recorded cases</span><strong>200 Hz</strong><span>control and contact intervals</span><strong>3</strong><span>physics timesteps in the sensitivity sweep</span></div></div>
    {error&&<p role="alert" className="dg-alert">{error}</p>}
    <section className="dg-panel"><h2>01 / Experiment matrix</h2><p>Fixed and scheduled gains cross no outage / 2 s outages. The ideal-feedback seed 301 sweep uses 5, 2.5 and 1.25 ms physics steps. Table metrics cover the full 50 s flight.</p><label>Sort cases<select aria-label="Sort cases" value={sort} onChange={e=>setSort(e.target.value)}><option value="id">Case</option><option value="residual">Momentum residual</option><option value="friction">Peak friction</option></select></label>
    <div className="friction-table"><table aria-label="Contact matrix"><thead><tr><th>Case</th><th>Mission</th><th>Physics ms</th><th>Residual N·s</th><th>Friction N</th></tr></thead><tbody>{[...cases].sort((a,b)=>sort==='id'?a.id.localeCompare(b.id):(b.summary[sort==='residual'?'momentum_with_friction_rms_ns':'peak_friction_n']??0)-(a.summary[sort==='residual'?'momentum_with_friction_rms_ns':'peak_friction_n']??0)).map(c=><tr key={c.id}><td><button aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}>{c.id}</button></td><td>{c.status}</td><td>{c.physics_dt_s*1000}</td><td>{fmt(c.summary.momentum_with_friction_rms_ns)}</td><td>{fmt(c.summary.peak_friction_n)}</td></tr>)}</tbody></table></div></section>
    {flight&&row&&metrics&&<><section className="dg-panel"><h2>02 / Inspect a landing</h2><p>{selected} · original mission: <strong>{flight.status}</strong> · {flight.failure_reason??'All original mission gates passed'}</p><div className="friction-controls"><label>Start s<input aria-label="Window start" type="number" min="0" max="49.995" step=".005" value={start} onChange={e=>windowChange(Number(e.target.value),end)}/></label><label>End s<input aria-label="Window end" type="number" min=".005" max="50" step=".005" value={end} onChange={e=>windowChange(start,Number(e.target.value))}/></label><button onClick={()=>windowChange(0,1)}>Initial support</button><button onClick={()=>windowChange(34,50)}>Landing</button><button onClick={()=>windowChange(48,50)}>Final support</button><button onClick={()=>{if(time>=end)setTime(start);setPlaying(!playing);}}>{playing?'Pause':'Play at ½ speed'}</button><button onClick={()=>setShow3d(!show3d)}>{show3d?'Hide':'Show'} 3D</button></div>
      <label>Cursor · {time.toFixed(3)} s<input aria-label="Replay time" type="range" min={start} max={end} step=".005" value={time} onChange={e=>seek(Number(e.target.value))}/></label>
      {show3d&&!failed3d&&<Suspense fallback={<p>Loading 3D scene…</p>}><Scene sample={pose(row)} samples={poses} rotorFlight visible onFailure={fail}/></Suspense>}{failed3d&&<p>3D unavailable; measured tables and plots remain available.</p>}
      <p>Pink: friction × 0.12 m/N, capped at 2 m. Green: normal × 0.06 m/N, capped at 1 m. Arrows show resultant forces; their display origins are schematic. Force at t belongs to the preceding 5 ms interval.</p>
      <div className="friction-stats">{Object.entries(metrics).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><strong>{fmt(v)}</strong></div>)}</div>
    </section><section className="dg-panel"><h2>03 / Force, impulse and work</h2><Plot title="Measured contact force (N)" rows={curves[0]} series={series(['Normal','Friction'])} start={start} end={end} time={time} onSeek={seek}/><Plot title="Momentum residual per interval (N·s)" rows={curves[1]} series={series(['Without friction','With measured friction'])} start={start} end={end} time={time} onSeek={seek}/><Plot title="Cumulative horizontal translational work (J)" rows={curves[2]} series={series(['Wind','Thrust','Friction','Kinetic change','Remaining residual'])} start={start} end={end} time={time} onSeek={seek}/><p>Momentum includes gravity and averaged applied world force over every physics substep. Work uses mean force × COM displacement. It excludes rotational/contact-point work and remains a discrete estimate.</p></section>
    <section className="dg-panel"><h2>04 / Sliding diagnostics</h2><Plot title="Tangential friction / normal force" rows={curves[3]} series={series(['Measured ratio','Dynamic material 0.5','Static material 0.7'])} start={start} end={end} time={time} onSeek={seek}/><Plot title="Friction alignment with midpoint COM velocity" rows={curves[4]} series={series(['Alignment cosine'])} start={start} end={end} time={time} onSeek={seek}/><p>−1 opposes COM motion; +1 follows it. Missing below 0.01 m/s or 1 μN. Gaps are omitted observations, not zero. Ratio requires normal &gt; 0.1 N; material coefficients are references, not flight acceptance limits. COM motion is not contact-point slip.</p></section>
    <section className="dg-panel"><h2>05 / Original gates and reproducible review</h2><div className="friction-table"><table><thead><tr><th>Gate</th><th>Result</th><th>Measured</th><th>Limit</th></tr></thead><tbody>{flight.gates.map(g=><tr key={g.id}><td>{g.label}</td><td>{g.status}</td><td>{fmt(g.value)} {g.unit}</td><td>{g.limit}</td></tr>)}</tbody></table></div><p>Source <code>{String(flight.source.source_commit)}</code></p><p>Capture <code>{flight.capture_sha256}</code></p><div className="friction-controls"><button onClick={()=>save(csv(flight,start,end),selected+'-intervals.csv','text/csv')}>Download interval CSV</button><button onClick={exportReview}>Download review JSON</button><button onClick={()=>{const p=new URLSearchParams({digest:indexSha256,case:selected,start:String(start),end:String(end),time:String(Math.round(time/.005)*.005)});history.replaceState(null,'','#'+p);setShare(location.href);}}>Create review link</button></div>{share&&<p className="friction-link">{share}</p>}<p>CSV includes interval endpoints (start, end]; JSON retains full traces, hashes and unchanged gates. Small synthetic cohorts do not establish hardware fidelity. AL-010 yaw refinement remains open.</p></section></>}
  </main>;
}

export function FrictionLive(){
  const [value,setValue]=useState<any>(null),[error,setError]=useState('');
  useEffect(()=>{let stopped=false;const a=new AbortController();async function poll(){try{const r=await fetch('/api/contact',{signal:a.signal,credentials:'omit',redirect:'error',cache:'no-store'});if(!r.ok)throw Error();const text=await r.text();if(text.length>4096)throw Error();const v=JSON.parse(text);if(v.state==='waiting'){if(!stopped)setValue(null);return;}if(v.schema_version!==1||!Number.isInteger(v.seed)||!Number.isFinite(v.time_s)||!Number.isFinite(v.age_s)||typeof v.stale!=='boolean'||!Number.isInteger(v.anchors)||!['normal_n','friction_n'].every(k=>Array.isArray(v[k])&&v[k].length===3&&v[k].every(Number.isFinite)))throw Error();if(!stopped){setValue(v);setError('');}}catch{if(!stopped){setValue(null);setError('Contact telemetry unavailable');}}}void poll();const id=setInterval(()=>void poll(),250);return()=>{stopped=true;a.abort();clearInterval(id);};},[]);
  return <main className="dg friction"><h1>Live ground contact</h1><p><a href="/">Open the flight monitor</a> · Simulation only · updates at 10 Hz</p>{error&&<p role="alert">{error}</p>}{value?<section className="dg-panel"><h2>{value.stale?'Stale / stopped capture':'Receiving contact forces'}</h2><p>Seed {value.seed} · {value.time_s.toFixed(3)} s · age {value.age_s.toFixed(2)} s</p><p>Normal (N): {value.normal_n.map(fmt).join(', ')}</p><p>Friction (N): {value.friction_n.map(fmt).join(', ')}</p><p>Friction anchors {value.anchors} / 64</p></section>:<p>Waiting for an instrumented flight.</p>}</main>;
}
